### ISSUE TITLE
peewee_migrate/router.py: module has no attribute '__path__'

### ISSUE THREAD

**Issue by ZhYong10** [klen/peewee_migrate#125]
File "/Users/anaconda3/lib/python3.6/site-packages/peewee_migrate/router.py", line 277, in _import_submodules
    if set(package.__path__) & passed:

AttributeError: module 'model' has no attribute '__path__'

**Comment by chobijaeyu** [comment]
`Exception has occurred: AttributeError
module 'model' has no attribute '__path__'
  File "/Users/dev/.pyenv/versions/3.6.5/lib/python3.6/site-packages/peewee_migrate/router.py", line 282, in _import_submodules
    if set(package.__path__) & passed:
  File "/Users/dev/.pyenv/versions/3.6.5/lib/python3.6/site-packages/peewee_migrate/router.py", line 268, in load_models
    modules = _import_submodules(module)
  File "/Users/dev/.pyenv/versions/3.6.5/lib/python3.6/site-packages/peewee_migrate/router.py", line 85, in <listcomp>
    models = [m for module in modules for m in load_models(module)]
  File "/Users/dev/.pyenv/versions/3.6.5/lib/python3.6/site-packages/peewee_migrate/router.py", line 88, in create
    return self.logger.error("Can't import models module: %s", auto)
  File "/Users/dev/Documents/python/base/pw_migrate.py", line 8, in <module>
    router.create(auto=model)
  File "/Users/dev/.pyenv/versions/3.6.5/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/dev/.pyenv/versions/3.6.5/lib/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/Users/dev/.pyenv/versions/3.6.5/lib/python3.6/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)`

migrate.py
`import model
from peewee_migrate import Router

model.database.connect()

router = Router(model.database,ignore='basemodel')

router.create(auto=model)
router.run

model.database.close()`


I get  same error .

**Comment by allankicker** [comment]
Same here with python3.5 :/: 
```
Traceback (most recent call last):
  File "/bin/pw_migrate", line 10, in <module>
    sys.exit(cli())
  File "/lib/python3.5/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/lib/python3.5/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/lib/python3.5/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/lib/python3.5/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/lib/python3.5/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/lib/python3.5/site-packages/peewee_migrate/cli.py", line 84, in create
    router.create(name, auto=auto)
  File "/lib/python3.5/site-packages/peewee_migrate/router.py", line 85, in create
    models = [m for module in modules for m in load_models(module)]
  File "/lib/python3.5/site-packages/peewee_migrate/router.py", line 85, in <listcomp>
    models = [m for module in modules for m in load_models(module)]
  File "/lib/python3.5/site-packages/peewee_migrate/router.py", line 268, in load_models
    modules = _import_submodules(module)
  File "/lib/python3.5/site-packages/peewee_migrate/router.py", line 282, in _import_submodules
    if set(package.__path__) & passed:
AttributeError: module 'app.models' has no attribute '__path__'
```

**Comment by Gaming32** [comment]
I'm still having this exact same issue today.
