### ISSUE TITLE
Auto-generated ForeignKeyField invalid syntax for rel_model

### ISSUE THREAD

**Issue by kolanos** [klen/peewee_migrate#14]
When auto-generating a migration the ForeignKeyField rel_model argument appears to be performing an str() on the related model class instead of an __name__.

    Start migrations
    invalid syntax (<string>, line 50)
    Traceback (most recent call last):
      File ".../venv/lib/python2.7/site-packages/peewee_migrate/router.py", line 111, in run_one
        migrate, rollback = self.read(name)
      File ".../venv/lib/python2.7/site-packages/peewee_migrate/router.py", line 209, in read
        exec_in(code, scope)
      File "<string>", line 3, in exec_in
      File "<string>", line 50
        organization = pw.ForeignKeyField(db_column='organization_id', rel_model=<class 'clams.blueprints.organization.models.Organization'>, related_name='organizationuser_set')
                                                                                 ^
    SyntaxError: invalid syntax
    Migration failed: 001_initial
    Traceback (most recent call last):
      File "manage.py", line 63, in <module>
        manager.run()
      File "/Users/kolanos/Web/clams/venv/lib/python2.7/site-packages/flask_script/__init__.py", line 412, in run
        result = self.handle(sys.argv[0], sys.argv[1:])
      File "/Users/kolanos/Web/clams/venv/lib/python2.7/site-packages/flask_script/__init__.py", line 383, in handle
        res = handle(*args, **config)
      File "/Users/kolanos/Web/clams/venv/lib/python2.7/site-packages/flask_script/commands.py", line 216, in __call__
        return self.run(*args, **kwargs)
      File "manage.py", line 41, in migrate
        migrations = router.run(name, fake=fake)
      File "/Users/kolanos/Web/clams/venv/lib/python2.7/site-packages/peewee_migrate/router.py", line 156, in run
        self.run_one(mname, migrator, fake=fake, force=fake)
      File "/Users/kolanos/Web/clams/venv/lib/python2.7/site-packages/peewee_migrate/router.py", line 111, in run_one
        migrate, rollback = self.read(name)
      File "/Users/kolanos/Web/clams/venv/lib/python2.7/site-packages/peewee_migrate/router.py", line 209, in read
        exec_in(code, scope)
      File "<string>", line 3, in exec_in
      File "<string>", line 50
        organization = pw.ForeignKeyField(db_column='organization_id', rel_model=<class 'models.Organization'>, related_name='organizationuser_set')
                                                                                 ^
    SyntaxError: invalid syntax

**Comment by klen** [comment]
Should be fixed now.

TODO: When model exists in migrator, use not class name but migrator.orm['model_name'] instead
