### ISSUE TITLE
Possibility for adding a not-null field with no default in a migration

### ISSUE THREAD

**Issue by dev-zero** [klen/peewee_migrate#18]
I am trying to add a not-null field in a migration. The way to do it is to add the fill with `null=True`, fill it and then add the not-null constraint.

I came up with the following:

``` python

    # add the field with null=True
    migrator.add_fields(
        'mymodel1',
        format = pw.CharField(max_length=255, null=True)
    )

    # initialize the format attribute
    migrator.sql("""
        UPDATE mymodel1 SET format = CASE WHEN (somerelatedtable.name LIKE '%-FOO') THEN 'FOO' ELSE 'BAR' END
            FROM somerelatedtable WHERE mymodel1.somerelatedtable_id = somerelatedtable.id;""")

    # add the not-null constraint
    migrator.add_not_null('mymodel1', 'format')
```

which fails with the following message:

```

Starting migrations
Running "002_pseudo_format"
add_column ('pseudopotential', 'format', <peewee.CharField object at 0x7fe224bb8518>)
format is not null but has no default
Traceback (most recent call last):
  File "/usr/lib64/python3.5/site-packages/peewee_migrate/router.py", line 128, in run_one
    migrator.run()
  File "/usr/lib64/python3.5/site-packages/peewee_migrate/migrator.py", line 108, in run
    opn.run()
  File "/usr/lib64/python3.5/site-packages/playhouse/migrate.py", line 144, in run
    getattr(self.migrator, self.method)(*self.args, **kwargs))
  File "/usr/lib64/python3.5/site-packages/playhouse/migrate.py", line 152, in inner
    return fn(self, *args, **kwargs)
  File "/usr/lib64/python3.5/site-packages/playhouse/migrate.py", line 222, in add_column
    raise ValueError('%s is not null but has no default' % column_name)
ValueError: format is not null but has no default
Migration failed: 002_pseudo_format
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.5/pw_migrate", line 9, in <module>
    load_entry_point('peewee-migrate==0.5.9', 'console_scripts', 'pw_migrate')()
  File "/usr/lib64/python3.5/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib64/python3.5/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/lib64/python3.5/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib64/python3.5/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib64/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib64/python3.5/site-packages/peewee_migrate/cli.py", line 57, in migrate
    migrations = router.run(name, fake=fake)
  File "/usr/lib64/python3.5/site-packages/peewee_migrate/router.py", line 156, in run
    self.run_one(mname, migrator, fake=fake, force=fake)
  File "/usr/lib64/python3.5/site-packages/peewee_migrate/router.py", line 128, in run_one
    migrator.run()
  File "/usr/lib64/python3.5/site-packages/peewee_migrate/migrator.py", line 108, in run
    opn.run()
  File "/usr/lib64/python3.5/site-packages/playhouse/migrate.py", line 144, in run
    getattr(self.migrator, self.method)(*self.args, **kwargs))
  File "/usr/lib64/python3.5/site-packages/playhouse/migrate.py", line 152, in inner
    return fn(self, *args, **kwargs)
  File "/usr/lib64/python3.5/site-packages/playhouse/migrate.py", line 222, in add_column
    raise ValueError('%s is not null but has no default' % column_name)
ValueError: format is not null but has no default
```

Removing the `add_not_null` makes it run through, but I should be able to have it completely in one migration, shouldn't I?

**Comment by dev-zero** [comment]
I guess the culprit is at https://github.com/klen/peewee_migrate/blob/develop/peewee_migrate/migrator.py#L243

**Comment by dev-zero** [comment]
Indeed, removing that line (and the corresponding line in 252) makes it work!

**Comment by dev-zero** [comment]
The problem with dropping the mentioned lines is that in future `--auto`-generated migrations peewee_migrate seems to re-add the not-null constraint as new change.

**Comment by klen** [comment]
Implemented: add_fields now accepts allow_not_null=True for NOT NULL columns without a default.
