### ISSUE TITLE
migrator.add_index fails with 'Relation ... already exists'

### ISSUE THREAD

**Issue by dev-zero** [klen/peewee_migrate#19]
I am trying to add an index as follows:

```python
migrator.add_index('structuresetstructure', 'structure', 'set', unique=True)
```

I get the following error:

```
[...]
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.5/pw_migrate", line 9, in <module>
    load_entry_point('peewee-migrate==0.5.10', 'console_scripts', 'pw_migrate')()
  File "/usr/lib64/python3.5/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib64/python3.5/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/lib64/python3.5/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib64/python3.5/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib64/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib64/python3.5/site-packages/peewee_migrate/cli.py", line 57, in migrate
    migrations = router.run(name, fake=fake)
  File "/usr/lib64/python3.5/site-packages/peewee_migrate/router.py", line 156, in run
    self.run_one(mname, migrator, fake=fake, force=fake)
  File "/usr/lib64/python3.5/site-packages/peewee_migrate/router.py", line 128, in run_one
    migrator.run()
  File "/usr/lib64/python3.5/site-packages/peewee_migrate/migrator.py", line 107, in run
    opn.run()
  File "/usr/lib64/python3.5/site-packages/playhouse/migrate.py", line 144, in run
    getattr(self.migrator, self.method)(*self.args, **kwargs))
  File "/usr/lib64/python3.5/site-packages/playhouse/migrate.py", line 133, in _handle_result
    self.execute(result)
  File "/usr/lib64/python3.5/site-packages/playhouse/migrate.py", line 129, in execute
    self.migrator.database.execute_sql(sql, params)
  File "/usr/lib64/python3.5/site-packages/playhouse/postgres_ext.py", line 380, in execute_sql
    self.commit()
  File "/usr/lib64/python3.5/site-packages/peewee.py", line 3316, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/usr/lib64/python3.5/site-packages/peewee.py", line 127, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib64/python3.5/site-packages/playhouse/postgres_ext.py", line 373, in execute_sql
    cursor.execute(sql, params or ())
peewee.ProgrammingError: FEHLER:  Relation „structuresetstructure_structure_id_set_id“ existiert bereits
```

I have another `add_index` call for a different table in an earlier (already applied) migration file.

**Comment by klen** [comment]
Hm, looks like you have this index already.

**Comment by dev-zero** [comment]
Kind of, yes. When I check the generated queries I see the query to add the index being generated twice. When I comment the `migrator.add_index` out, I don't get it at all.

**Comment by tymofij** [comment]
I still experience this error in 1.0 and 0.14.0
It happens when I try to add an index on the field which was created in the same migration.

```
diff --git a/tests/migrations/002_test.py b/tests/migrations/002_test.py
index bf5791f..afa1740 100644
--- a/tests/migrations/002_test.py
+++ b/tests/migrations/002_test.py
@@ -29,4 +29,5 @@ def migrate(migrator, database, **kwargs):
     migrator.add_fields(
         'tag', created_at=pw.DateTimeField(null=True))

+    migrator.add_index('tag', 'created_at', unique=False)
     migrator.add_index('person', 'first_name', unique=True)
```

> sqlite3.OperationalError: index tag_created_at already exists
