### ISSUE TITLE
AttributeError: 'MySQLMigrator' object has no attribute 'change_column'

### ISSUE THREAD

**Issue by joshdavey** [klen/peewee_migrate#21]
Hey, I'm trying to change a column like so...

`migrator.change_fields('user', email=pw.CharField(max_length=100, null=True))`

But I end up with the following error...

```
Traceback (most recent call last):
  File "scripts/reload_local.py", line 108, in <module>
    router.run()
  File "/usr/local/lib/python3.5/dist-packages/peewee_migrate/router.py", line 158, in run
    self.run_one(mname, migrator, fake=fake, force=fake)
  File "/usr/local/lib/python3.5/dist-packages/peewee_migrate/router.py", line 129, in run_one
    migrate(migrator, self.database, fake=fake)
  File "<string>", line 46, in migrate
  File "/usr/local/lib/python3.5/dist-packages/peewee_migrate/migrator.py", line 102, in wrapper
    return method(migrator, migrator.orm[model], *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/peewee_migrate/migrator.py", line 184, in change_columns
    self.ops.append(self.migrator.change_column(
AttributeError: 'MySQLMigrator' object has no attribute 'change_column'
```

I'm using MySQL. 

Thanks for any help!

Cheers

**Comment by klen** [comment]
I've added a basic support for this, but didn't test.
