### ISSUE TITLE
crashes with python 3

### ISSUE THREAD

**Issue by vanzhiganov** [klen/peewee_migrate#68]
Traceback (most recent call last):
  File "/Users/v/.venv/s/bin/pw_migrate", line 7, in <module>
    from peewee_migrate.cli import cli
  File "/Users/v/.venv/s/lib/python3.6/site-packages/peewee_migrate/__init__.py", line 36, in <module>
    from .router import Migrator, Router # noqa
  File "/Users/v/.venv/s/lib/python3.6/site-packages/peewee_migrate/router.py", line 14, in <module>
    from peewee_migrate.migrator import Migrator
  File "/Users/v/.venv/s/lib/python3.6/site-packages/peewee_migrate/migrator.py", line 2, in <module>
    from playhouse.migrate import (
ImportError: cannot import name 'Clause'

**Comment by ShipraShalini** [comment]
Crashes with peewee 3.0.8.

**Comment by vanzhiganov** [comment]
@ShipraShalini Thank you for this idea, i was downgrade the peewee to version 2.10.2 and it works for me.

**Comment by Relrin** [comment]
Have got recently the same issue with installing this package. Downgrade helped me as well.
This issue comes, as far as I understood, from the first 3.* releases of Peewee ORM, because on their docs mentioned that third version isn't compatible with 2.* versions.
